### PR TITLE
Add option to hide background colors

### LINKED ISSUE #7: Needs theme with no background color
I use a black background in my terminal, and the "dark" themes aren't really enough. Either having a black theme or one without background color (meaning using the terminal's background) would be ideal.

Great project!

### PR DESCRIPTION
**Pull request by controversial**
Added a config option called hide-background which, when enabled, will render the following colors with transparent backgrounds:
- COMMIT_HEADER_COLOR
- COMMIT_MESSAGE_COLOR
- BORDER_COLOR
- FILE_NAME_COLOR
- UNMODIFIED_LINE_NO_COLOR
- UNMODIFIED_LINE_COLOR
- MISSING_LINE_COLOR

The result (using `github-dark-dim`):

Screen Shot 2021-05-01 at 9 22 06 PM

It's somewhat debatable whether HUNK_HEADER_COLOR should be included as well

Closes #7

### CODE REVIEW

**Comment by controversial** [comment]
Closes #7

**Review by Cretezy — APPROVED** [review]

**Comment by banga** [comment]
Nice! Thanks for working on this. I have a slightly different approach in mind so I'm going to take a stab at that first instead, hope you don't mind.

**Comment by controversial** [comment]
No worries, it's your project!

**Comment by gabriel-del** [comment]
It's great, I'm looking for a theme like this.

**Comment by camina-apps** [comment]
would like to see something like this

**Comment by z01cbrag** [comment]
That'd really be great 👍

**Pull request closed without merging**
